/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class JDlgVenda_produto_aus extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVenda_produto_aus
     */
    public JDlgVenda_produto_aus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCodigo_produtos_aus = new javax.swing.JTextField();
        jTxtQuantidade_aus = new javax.swing.JTextField();
        jTxtObservacao_aus = new javax.swing.JTextField();
        jTxtDesconto_aus = new javax.swing.JTextField();
        jTxtPreco_unitario_aus = new javax.swing.JTextField();
        jBtnIncluir_aus = new javax.swing.JButton();
        jBtnAlterar_aus = new javax.swing.JButton();
        jBtnExcluir_aus = new javax.swing.JButton();
        jBtnConfirmar_aus = new javax.swing.JButton();
        jBtnCancelar_aus = new javax.swing.JButton();
        jBtnPesquisar_aus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo venda produtos");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Observacao");

        jLabel4.setText("Preco unitario");

        jLabel5.setText("Desconto");

        jBtnIncluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_aus.setText("Incluir");
        jBtnIncluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ausActionPerformed(evt);
            }
        });

        jBtnAlterar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar_aus.setText("Alterar");
        jBtnAlterar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ausActionPerformed(evt);
            }
        });

        jBtnExcluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir_aus.setText("Excluir");
        jBtnExcluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ausActionPerformed(evt);
            }
        });

        jBtnConfirmar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar_aus.setText("Confirmar");
        jBtnConfirmar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ausActionPerformed(evt);
            }
        });

        jBtnCancelar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar_aus.setText("Cancelar");
        jBtnCancelar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ausActionPerformed(evt);
            }
        });

        jBtnPesquisar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_aus.setText("Pesquisar");
        jBtnPesquisar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ausActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtCodigo_produtos_aus)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtQuantidade_aus, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addComponent(jTxtObservacao_aus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(161, 161, 161))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jTxtDesconto_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(117, 117, 117)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPreco_unitario_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnIncluir_aus)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar_aus)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir_aus)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmar_aus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar_aus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPesquisar_aus)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigo_produtos_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDesconto_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQuantidade_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPreco_unitario_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTxtObservacao_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_aus)
                    .addComponent(jBtnAlterar_aus)
                    .addComponent(jBtnExcluir_aus)
                    .addComponent(jBtnConfirmar_aus)
                    .addComponent(jBtnCancelar_aus)
                    .addComponent(jBtnPesquisar_aus))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluir_ausActionPerformed

    private void jBtnAlterar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterar_ausActionPerformed

    private void jBtnExcluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ausActionPerformed
        // TODO add your handling code here:
        //        int resp = JOptionPane.showConfirmDialog(null,
            //                "Deseja excluir o registro", "Aviso",
            //                JOptionPane.YES_NO_OPTION);
        //        if (resp == JOptionPane.YES_OPTION) {
            //            Mecc_usuario usuario = new Mecc_usuario();
            //            int cod = Integer.valueOf(jTxtCodigo.getText());
            //            usuario.setMecc_idusuario(cod);
            //            usuario.setMecc_nome(jTxtNome.getText());
            //            usuario.setMecc_apelido(jTxtApelido.getText());
            //            usuario.setMecc_cpf(jTxtCpf.getText());
            //            usuario.setMecc_senha(jTxtSenha.getText());
            //            usuario.setMecc_dataNascimento(null);//jTxtDatanasc.getText());
        //            usuario.setMecc_nivel(jCboNivel.getSelectedIndex());
        //            if (jChbAtivo.isSelected() == true) {
            //                usuario.setMecc_ativo("S");
            //            } else {
            //                usuario.setMecc_ativo("N");
            //            }
        //            Mecc_usuarioDAO usuarioDAO = new Mecc_usuarioDAO();
        //            usuarioDAO.delete(usuario);
        //
        //            JOptionPane.showMessageDialog(null, "Exclusão Realizada.");
        //        } else {
        //            JOptionPane.showMessageDialog(null, "Exclusão Cancelada");
        //
        //    }
        //        desabilitar();
    }//GEN-LAST:event_jBtnExcluir_ausActionPerformed

    private void jBtnConfirmar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ausActionPerformed
        // TODO add your handling code here:
        //        Mecc_usuario usuario = new Mecc_usuario();
        //        int cod = Integer.valueOf(jTxtCodigo.getText());
        //        usuario.setMecc_idusuario(cod);
        //        usuario.setMecc_nome(jTxtNome.getText());
        //        usuario.setMecc_apelido(jTxtApelido.getText());
        //        usuario.setMecc_cpf(jTxtCpf.getText());
        //        usuario.setMecc_senha(jTxtSenha.getText());
        //        usuario.setMecc_dataNascimento(null);//jTxtDatanasc.getText());
        //        usuario.setMecc_nivel(jCboNivel.getSelectedIndex());
        //        if (jChbAtivo.isSelected() == true) {
            //            usuario.setMecc_ativo("S");
            //        } else {
            //            usuario.setMecc_ativo("N");
            //        }
        //
        //        Mecc_usuarioDAO mecc_usuarioDAO = new Mecc_usuarioDAO();
        //        mecc_usuarioDAO.insert(usuario);
        //        desabilitar();
    }//GEN-LAST:event_jBtnConfirmar_ausActionPerformed

    private void jBtnCancelar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelar_ausActionPerformed

    private void jBtnPesquisar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ausActionPerformed
        // TODO add your handling code here:
        //        String resp = JOptionPane.showInputDialog(null, "Entre com o código: ");
        //        Mecc_usuarioDAO mecc_usuarioDAO = new Mecc_usuarioDAO();
        //
        //        int cod = Integer.parseInt(resp);
        //        Mecc_usuario usuario = (Mecc_usuario) mecc_usuarioDAO.list(cod);
        //        String cad = String.valueOf(usuario.getMecc_idusuario());
        //        jTxtCodigo.setText(cad);
        //        jTxtNome.setText(usuario.getMecc_nome());
        //        jTxtApelido.setText(usuario.getMecc_apelido());
        //        jTxtCpf.setText(usuario.getMecc_cpf());
        //        jTxtSenha.setText(usuario.getMecc_senha());
        //        //jTxtDatanasc.setText( usuario.getMecc_DataNascimento));
        //        jCboNivel.setSelectedIndex(usuario.getMecc_nivel());
        //        if (usuario.getMecc_ativo().equals("S") == true) {
            //            jChbAtivo.setSelected(true);
            //        } else {
            //            jChbAtivo.setSelected(false);
            //        }
    }//GEN-LAST:event_jBtnPesquisar_ausActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_produto_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_produto_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_produto_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_produto_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVenda_produto_aus dialog = new JDlgVenda_produto_aus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_aus;
    private javax.swing.JButton jBtnCancelar_aus;
    private javax.swing.JButton jBtnConfirmar_aus;
    private javax.swing.JButton jBtnExcluir_aus;
    private javax.swing.JButton jBtnIncluir_aus;
    private javax.swing.JButton jBtnPesquisar_aus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtCodigo_produtos_aus;
    private javax.swing.JTextField jTxtDesconto_aus;
    private javax.swing.JTextField jTxtObservacao_aus;
    private javax.swing.JTextField jTxtPreco_unitario_aus;
    private javax.swing.JTextField jTxtQuantidade_aus;
    // End of variables declaration//GEN-END:variables
}
