/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class JDlgVendas_aus extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVendas_aus
     */
    public JDlgVendas_aus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Transporte = new javax.swing.JLabel();
        jTxt_vendas_aus = new javax.swing.JTextField();
        jTxtData_aus = new javax.swing.JTextField();
        jTxtCliente_aus = new javax.swing.JTextField();
        jTxtVendedor_aus = new javax.swing.JTextField();
        jTxtDesconto_aus = new javax.swing.JTextField();
        Transporte1 = new javax.swing.JLabel();
        jTxtForma_aus = new javax.swing.JTextField();
        Transporte2 = new javax.swing.JLabel();
        jCboStatus_aus = new javax.swing.JComboBox<>();
        jBtnIncluir_aus = new javax.swing.JButton();
        jBtnAlterar_aus = new javax.swing.JButton();
        jBtnExcluir_aus = new javax.swing.JButton();
        jBtnConfirmar_aus = new javax.swing.JButton();
        jBtnCancelar_aus = new javax.swing.JButton();
        jBtnPesquisar_aus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo vendas");

        jLabel2.setText("Data ");

        jLabel3.setText("Cliente");

        jLabel4.setText("Vendedor");

        Transporte.setText("Status da Venda");

        jTxt_vendas_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_vendas_ausActionPerformed(evt);
            }
        });

        jTxtData_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtData_ausActionPerformed(evt);
            }
        });

        jTxtVendedor_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVendedor_ausActionPerformed(evt);
            }
        });

        Transporte1.setText("Transporte");

        Transporte2.setText("Forma de pagamento");

        jCboStatus_aus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em andamento ", "Pago ", "Cancelado" }));

        jBtnIncluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_aus.setText("Incluir");
        jBtnIncluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ausActionPerformed(evt);
            }
        });

        jBtnAlterar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar_aus.setText("Alterar");
        jBtnAlterar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ausActionPerformed(evt);
            }
        });

        jBtnExcluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir_aus.setText("Excluir");
        jBtnExcluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ausActionPerformed(evt);
            }
        });

        jBtnConfirmar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar_aus.setText("Confirmar");
        jBtnConfirmar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ausActionPerformed(evt);
            }
        });

        jBtnCancelar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar_aus.setText("Cancelar");
        jBtnCancelar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ausActionPerformed(evt);
            }
        });

        jBtnPesquisar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_aus.setText("Pesquisar");
        jBtnPesquisar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ausActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir_aus)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterar_aus)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExcluir_aus)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConfirmar_aus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar_aus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPesquisar_aus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtCliente_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(239, 239, 239)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtForma_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Transporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboStatus_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxt_vendas_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(194, 194, 194))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(200, 200, 200)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtData_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(239, 239, 239)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDesconto_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtVendedor_aus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Transporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_vendas_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVendedor_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Transporte1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtData_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDesconto_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Transporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboStatus_aus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTxtCliente_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Transporte2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtForma_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_aus)
                    .addComponent(jBtnAlterar_aus)
                    .addComponent(jBtnExcluir_aus)
                    .addComponent(jBtnConfirmar_aus)
                    .addComponent(jBtnCancelar_aus)
                    .addComponent(jBtnPesquisar_aus))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_vendas_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_vendas_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_vendas_ausActionPerformed

    private void jTxtVendedor_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVendedor_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtVendedor_ausActionPerformed

    private void jTxtData_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtData_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtData_ausActionPerformed

    private void jBtnIncluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ausActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnIncluir_ausActionPerformed

    private void jBtnAlterar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ausActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnAlterar_ausActionPerformed

    private void jBtnExcluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ausActionPerformed
        // TODO add your handling code here:
        //        int resp = JOptionPane.showConfirmDialog(null,
            //                "Deseja excluir o registro", "Aviso",
            //                JOptionPane.YES_NO_OPTION);
        //        if (resp == JOptionPane.YES_OPTION) {
            //            Mecc_usuario usuario = new Mecc_usuario();
            //            int cod = Integer.valueOf(jTxtCodigo.getText());
            //            usuario.setMecc_idusuario(cod);
            //            usuario.setMecc_nome(jTxtNome.getText());
            //            usuario.setMecc_apelido(jTxtApelido.getText());
            //            usuario.setMecc_cpf(jTxtCpf.getText());
            //            usuario.setMecc_senha(jTxtSenha.getText());
            //            usuario.setMecc_dataNascimento(null);//jTxtDatanasc.getText());
        //            usuario.setMecc_nivel(jCboNivel.getSelectedIndex());
        //            if (jChbAtivo.isSelected() == true) {
            //                usuario.setMecc_ativo("S");
            //            } else {
            //                usuario.setMecc_ativo("N");
            //            }
        //            Mecc_usuarioDAO usuarioDAO = new Mecc_usuarioDAO();
        //            usuarioDAO.delete(usuario);
        //
        //            JOptionPane.showMessageDialog(null, "Exclusão Realizada.");
        //        } else {
        //            JOptionPane.showMessageDialog(null, "Exclusão Cancelada");
        //
        //    }
        //        desabilitar();
    }//GEN-LAST:event_jBtnExcluir_ausActionPerformed

    private void jBtnConfirmar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ausActionPerformed
        // TODO add your handling code here:
        //        Mecc_usuario usuario = new Mecc_usuario();
        //        int cod = Integer.valueOf(jTxtCodigo.getText());
        //        usuario.setMecc_idusuario(cod);
        //        usuario.setMecc_nome(jTxtNome.getText());
        //        usuario.setMecc_apelido(jTxtApelido.getText());
        //        usuario.setMecc_cpf(jTxtCpf.getText());
        //        usuario.setMecc_senha(jTxtSenha.getText());
        //        usuario.setMecc_dataNascimento(null);//jTxtDatanasc.getText());
        //        usuario.setMecc_nivel(jCboNivel.getSelectedIndex());
        //        if (jChbAtivo.isSelected() == true) {
            //            usuario.setMecc_ativo("S");
            //        } else {
            //            usuario.setMecc_ativo("N");
            //        }
        //
        //        Mecc_usuarioDAO mecc_usuarioDAO = new Mecc_usuarioDAO();
        //        mecc_usuarioDAO.insert(usuario);
        //        desabilitar();
    }//GEN-LAST:event_jBtnConfirmar_ausActionPerformed

    private void jBtnCancelar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ausActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnCancelar_ausActionPerformed

    private void jBtnPesquisar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ausActionPerformed
        // TODO add your handling code here:
        //        String resp = JOptionPane.showInputDialog(null, "Entre com o código: ");
        //        Mecc_usuarioDAO mecc_usuarioDAO = new Mecc_usuarioDAO();
        //
        //        int cod = Integer.parseInt(resp);
        //        Mecc_usuario usuario = (Mecc_usuario) mecc_usuarioDAO.list(cod);
        //        String cad = String.valueOf(usuario.getMecc_idusuario());
        //        jTxtCodigo.setText(cad);
        //        jTxtNome.setText(usuario.getMecc_nome());
        //        jTxtApelido.setText(usuario.getMecc_apelido());
        //        jTxtCpf.setText(usuario.getMecc_cpf());
        //        jTxtSenha.setText(usuario.getMecc_senha());
        //        //jTxtDatanasc.setText( usuario.getMecc_DataNascimento));
        //        jCboNivel.setSelectedIndex(usuario.getMecc_nivel());
        //        if (usuario.getMecc_ativo().equals("S") == true) {
            //            jChbAtivo.setSelected(true);
            //        } else {
            //            jChbAtivo.setSelected(false);
            //        }
    }//GEN-LAST:event_jBtnPesquisar_ausActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas_aus dialog = new JDlgVendas_aus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Transporte;
    private javax.swing.JLabel Transporte1;
    private javax.swing.JLabel Transporte2;
    private javax.swing.JButton jBtnAlterar_aus;
    private javax.swing.JButton jBtnCancelar_aus;
    private javax.swing.JButton jBtnConfirmar_aus;
    private javax.swing.JButton jBtnExcluir_aus;
    private javax.swing.JButton jBtnIncluir_aus;
    private javax.swing.JButton jBtnPesquisar_aus;
    private javax.swing.JComboBox<String> jCboStatus_aus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtCliente_aus;
    private javax.swing.JTextField jTxtData_aus;
    private javax.swing.JTextField jTxtDesconto_aus;
    private javax.swing.JTextField jTxtForma_aus;
    private javax.swing.JTextField jTxtVendedor_aus;
    private javax.swing.JTextField jTxt_vendas_aus;
    // End of variables declaration//GEN-END:variables
}
