/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import javax.swing.JOptionPane;

/**
 *
 * @author urban
 */
public class JDlgProdutos_aus extends javax.swing.JDialog {

    /**
     * Creates new form JDlgProdutos
     */
    public JDlgProdutos_aus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro do Produto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        JLabel7 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        jTxtNome_aus = new javax.swing.JTextField();
        jTxtValidade_aus = new javax.swing.JTextField();
        jTxtVolume_aus = new javax.swing.JTextField();
        jTxtMarca_aus = new javax.swing.JTextField();
        jTxtAreaDoRosto_aus = new javax.swing.JTextField();
        jTxtComponentes_aus = new javax.swing.JTextField();
        jTxtRestricoes_aus = new javax.swing.JTextField();
        jBtnIncluir_aus = new javax.swing.JButton();
        jBtnAlterar_aus = new javax.swing.JButton();
        jBtnExcluir_aus = new javax.swing.JButton();
        jBtnConfirmar_aus = new javax.swing.JButton();
        jBtnCancelar_aus = new javax.swing.JButton();
        jBtnPesquisar_aus = new javax.swing.JButton();
        jTxtCodigo_aus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLabel1.setText("Nome");

        JLabel5.setText("Validade");

        JLabel2.setText("Volume");

        JLabel6.setText("Marca");

        JLabel3.setText("Area do Rosto");

        JLabel7.setText("Componentes");

        JLabel4.setText("Restrições");

        jTxtAreaDoRosto_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAreaDoRosto_ausActionPerformed(evt);
            }
        });

        jBtnIncluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_aus.setText("Incluir");
        jBtnIncluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ausActionPerformed(evt);
            }
        });

        jBtnAlterar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar_aus.setText("Alterar");
        jBtnAlterar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ausActionPerformed(evt);
            }
        });

        jBtnExcluir_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir_aus.setText("Ecluir");
        jBtnExcluir_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ausActionPerformed(evt);
            }
        });

        jBtnConfirmar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar_aus.setText("Confirmar");
        jBtnConfirmar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ausActionPerformed(evt);
            }
        });

        jBtnCancelar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jBtnCancelar_aus.setText("Cancelar");
        jBtnCancelar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ausActionPerformed(evt);
            }
        });

        jBtnPesquisar_aus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_aus.setText("Pesquisar");
        jBtnPesquisar_aus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ausActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo dos produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel5)
                    .addComponent(JLabel1)
                    .addComponent(jLabel1)
                    .addComponent(JLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir_aus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAlterar_aus)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir_aus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnConfirmar_aus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_aus)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPesquisar_aus)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtCodigo_aus, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jTxtValidade_aus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtVolume_aus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNome_aus, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabel4)
                            .addComponent(JLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabel6)
                                    .addComponent(JLabel7))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtMarca_aus, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jTxtAreaDoRosto_aus)
                                    .addComponent(jTxtRestricoes_aus)
                                    .addComponent(jTxtComponentes_aus))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCodigo_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(JLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxtMarca_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel1)
                    .addComponent(JLabel3)
                    .addComponent(jTxtAreaDoRosto_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtValidade_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel5)
                    .addComponent(JLabel7)
                    .addComponent(jTxtComponentes_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtVolume_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabel4)
                            .addComponent(jTxtRestricoes_aus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_aus)
                    .addComponent(jBtnAlterar_aus)
                    .addComponent(jBtnExcluir_aus)
                    .addComponent(jBtnConfirmar_aus)
                    .addComponent(jBtnCancelar_aus)
                    .addComponent(jBtnPesquisar_aus))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluir_ausActionPerformed

    private void jBtnAlterar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterar_ausActionPerformed

    private void jBtnExcluir_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ausActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBtnExcluir_ausActionPerformed

    private void jBtnConfirmar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ausActionPerformed

    }//GEN-LAST:event_jBtnConfirmar_ausActionPerformed

    private void jBtnCancelar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelar_ausActionPerformed

    private void jBtnPesquisar_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ausActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBtnPesquisar_ausActionPerformed

    private void jTxtAreaDoRosto_ausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAreaDoRosto_ausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAreaDoRosto_ausActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos_aus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutos_aus dialog = new JDlgProdutos_aus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JButton jBtnAlterar_aus;
    private javax.swing.JButton jBtnCancelar_aus;
    private javax.swing.JButton jBtnConfirmar_aus;
    private javax.swing.JButton jBtnExcluir_aus;
    private javax.swing.JButton jBtnIncluir_aus;
    private javax.swing.JButton jBtnPesquisar_aus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtAreaDoRosto_aus;
    private javax.swing.JTextField jTxtCodigo_aus;
    private javax.swing.JTextField jTxtComponentes_aus;
    private javax.swing.JTextField jTxtMarca_aus;
    private javax.swing.JTextField jTxtNome_aus;
    private javax.swing.JTextField jTxtRestricoes_aus;
    private javax.swing.JTextField jTxtValidade_aus;
    private javax.swing.JTextField jTxtVolume_aus;
    // End of variables declaration//GEN-END:variables
}
